site_name: Cours de programmation OO 1
repo_url: https://github.com/profdenis/2N1_doc

theme: 
  name: readthedocs
  locale: fr
  color_mode: auto
  user_color_mode_toggle: true

extra_css:
  - style.css

markdown_extensions:
  smarty: {}
  toc:
    permalink: true
  sane_lists: {}
  admonition: {}
  codehilite: {}
  pymdownx.superfences: {}
  pymdownx.fancylists: {}
  pymdownx.saneheaders: {}
  pymdownx.mark: {}
  pymdownx.tabbed: {}
  pymdownx.tasklist: {}
  pymdownx.tilde: {}
  pymdownx.details: {}
  pymdownx.arithmatex:
    generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
        theme:
          enabled: false

